platform:
  - x64

install:
  - set PATH=C:\Ruby23-x64\bin;%PATH%
  - ps: Install-Product node 6 x64
  - yarn install

build_script:
  - yarn help

test_script:
  - node_modules/.bin/grunt test

artifacts:
  - path: dist/*.*

environment:
  SIGNAL_ENV: production

deploy:
  provider: Environment
  name: signal-desktop-builds
